spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"

loans:
  message: "Welcome to Aluri Loans related PROD APIs"
  contactDetails:
    name: "Mounika Lamu - Tester"
    email: "mounika.lamu@ibm.com"
  onCallSupport:
    - (452)456-3178
    - (687)764-8943