spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to Aluri accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray"
    email: "smitha.ray@aluri.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345